# Generated by Django 6.1.1 on 2026-09-13 04:51

import apps.audit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("materials", "0001_initial"),
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "audit_log_id",
                    apps.audit.models.UUIDv7Field(
                        default=apps.audit.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                            ("user_create", "User create"),
                            ("deactivate", "Deactivate account"),
                            ("deactivate_blocked", "Deactivate account blocked"),
                            ("reactivate", "Reactivate account"),
                            ("password_reset", "Password reset"),
                            ("password_reset_by_admin", "Password reset by admin"),
                            ("material_upload", "Material upload"),
                            ("material_update", "Material update"),
                            ("material_delete", "Material delete"),
                            ("material_download", "Material download"),
                            ("material_approve", "Material approve"),
                            ("material_reject", "Material reject"),
                            ("quiz_start", "Quiz start"),
                            ("quiz_submit", "Quiz submit"),
                            ("comment_delete", "Comment delete"),
                            ("report_dismiss", "Report dismiss"),
                            ("lesson_create", "Lesson create"),
                            ("lesson_approve", "Lesson approve"),
                            ("lesson_reject", "Lesson reject"),
                            ("quiz_create", "Quiz create"),
                            ("quiz_approve", "Quiz approve"),
                            ("quiz_reject", "Quiz reject"),
                            ("quiz_disable", "Quiz disable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "target_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="materials.material",
                    ),
                ),
                (
                    "target_quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-audit_log_id"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_action_time_idx"
                    ),
                    models.Index(
                        fields=["target_material", "action", "created_at"],
                        name="audit_material_event_idx",
                    ),
                ],
            },
        ),
    ]
