# Generated by Django 6.1.1 on 2026-09-13 04:51

import apps.accounts.models
import apps.materials.models
import apps.materials.storage
import apps.materials.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialSubmission",
            fields=[
                (
                    "submission_id",
                    apps.accounts.models.UUIDv7Field(
                        default=apps.accounts.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("review_locked_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_submissions",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-submission_id"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "material_id",
                    apps.accounts.models.UUIDv7Field(
                        default=apps.accounts.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("slides", "Slides"),
                            ("exercise", "Exercise"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.materials.storage.PrivateS3Storage(),
                        upload_to=apps.materials.models.material_upload_path,
                        validators=[apps.materials.validators.validate_material_file],
                    ),
                ),
                (
                    "converted_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.materials.storage.PrivateS3Storage(),
                        upload_to=apps.materials.models.converted_pdf_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="materials.materialsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "material_id"],
            },
        ),
        migrations.AddIndex(
            model_name="materialsubmission",
            index=models.Index(
                fields=["status", "deleted_at", "-created_at"],
                name="submission_catalog_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialsubmission",
            index=models.Index(
                fields=["owner", "deleted_at"], name="submission_owner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["submission"], name="material_submission_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["owner"], name="material_owner_idx"),
        ),
    ]
